packages:
  - .
  - vendor/discord-video-stream
  - vendor/discord.js-selfbot-v13

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@lng2004/node-datachannel'
  - better-sqlite3
  - esbuild
  - node-av
  - sharp
  - zeromq
