export interface SlangLexiconEntry {
  normalized: string;
  note: string;
  safeByDefault?: boolean;
}

export const INDONESIAN_SLANG_LEXICON: Record<string, SlangLexiconEntry> = {
  gw: { normalized: "gue", note: "first-person informal pronoun" },
  gue: { normalized: "gue", note: "first-person informal pronoun" },
  gua: { normalized: "gue", note: "first-person informal pronoun" },
  lo: { normalized: "lu", note: "second-person informal pronoun" },
  lu: { normalized: "lu", note: "second-person informal pronoun" },
  loe: { normalized: "lu", note: "second-person informal pronoun" },
  yg: { normalized: "yang", note: "common abbreviation" },
  emg: { normalized: "memang", note: "common abbreviation" },
  kyk: { normalized: "kayak", note: "common abbreviation" },
  tdk: { normalized: "tidak", note: "common abbreviation" },
  krn: { normalized: "karena", note: "common abbreviation" },
  jgn: { normalized: "jangan", note: "common abbreviation" },
  // Indonesian swear-word slang variants — normalize to standard form so the
  // badwords detector can recognise them.  These are NOT safeByDefault because
  // they map to genuine Indonesian profanity.
  ajg: { normalized: "anjing", note: "slang for 'anjing' (profanity)" },
  anjg: { normalized: "anjing", note: "slang for 'anjing' (profanity)" },
  njing: { normalized: "anjing", note: "slang for 'anjing' (profanity)" },
  anjir: { normalized: "anjing", note: "slang for 'anjing' (profanity)" },
  njir: { normalized: "anjing", note: "slang for 'anjing' (profanity)" },
  bgsd: { normalized: "bangsat", note: "slang for 'bangsat' (profanity)" },
  bgst: { normalized: "bangsat", note: "slang for 'bangsat' (profanity)" },
  bngst: { normalized: "bangsat", note: "slang for 'bangsat' (profanity)" },
  brngsk: { normalized: "brengsek", note: "slang for 'brengsek' (profanity)" },
  bjngn: { normalized: "bajingan", note: "slang for 'bajingan' (profanity)" },
  bjgn: { normalized: "bajingan", note: "slang for 'bajingan' (profanity)" },
  kntl: { normalized: "kontol", note: "slang for 'kontol' (profanity)" },
  knt: { normalized: "kontol", note: "slang for 'kontol' (profanity)" },
  kontl: { normalized: "kontol", note: "slang for 'kontol' (profanity)" },
  mmk: { normalized: "memek", note: "slang for 'memek' (profanity)" },
  memk: { normalized: "memek", note: "slang for 'memek' (profanity)" },
  tae: { normalized: "tai", note: "slang for 'tai' (profanity)" },
  ty: { normalized: "tai", note: "slang for 'tai' (profanity)" },
  gblk: { normalized: "goblok", note: "slang for 'goblok' (profanity)" },
  goblog: { normalized: "goblok", note: "slang for 'goblok' (profanity)" },
  tlol: { normalized: "tolol", note: "slang for 'tolol' (profanity)" },
  bgo: { normalized: "bego", note: "slang for 'bego' (profanity)" },
  slan: { normalized: "sialan", note: "slang for 'sialan' (profanity)" },
  sln: { normalized: "sialan", note: "slang for 'sialan' (profanity)" },
  jncuk: { normalized: "jancuk", note: "Javanese slang for 'jancuk' (profanity)" },
  jcuk: { normalized: "jancuk", note: "Javanese slang for 'jancuk' (profanity)" },
  kmprt: { normalized: "kampret", note: "slang for 'kampret' (profanity)" },
  ppk: { normalized: "pepek", note: "slang for 'pepek' (profanity)" },
  jmbt: { normalized: "jembut", note: "slang for 'jembut' (profanity)" },
  ngntt: { normalized: "ngentot", note: "slang for 'ngentot' (profanity)" },
  ngnt: { normalized: "ngentot", note: "slang for 'ngentot' (profanity)" },
  ngw: { normalized: "ngewe", note: "slang for 'ngewe' (profanity)" },
  cli: { normalized: "coli", note: "slang for 'coli' (profanity)" },
  clka: { normalized: "celaka", note: "slang for 'celaka' (profanity)" },
  lknt: { normalized: "laknat", note: "slang for 'laknat' (profanity)" },
  bngsat: { normalized: "bangsat", note: "slang for 'bangsat' (profanity)" },
  bgsat: { normalized: "bangsat", note: "slang for 'bangsat' (profanity)" },
  // Sexual deviation / prohibited identity topics — normalize so badwords
  // detector and LLM can recognise them.  These are NOT safeByDefault.
  lgbt: { normalized: "LGBT", note: "sexual deviation / prohibited topic" },
  lgbtq: { normalized: "LGBTQ", note: "sexual deviation / prohibited topic" },
  lgbtqi: { normalized: "LGBTQI", note: "sexual deviation / prohibited topic" },
  lgbtqa: { normalized: "LGBTQA", note: "sexual deviation / prohibited topic" },
  furry: { normalized: "furry", note: "sexual deviation / prohibited topic" },
  furries: { normalized: "furry", note: "sexual deviation / prohibited topic" },
  transfurry: { normalized: "transfurry", note: "sexual deviation / prohibited topic" },
  protogen: { normalized: "protogen", note: "furry subculture / prohibited topic" },
  therian: { normalized: "therian", note: "therianthropy / prohibited topic" },
  otherkin: { normalized: "otherkin", note: "otherkin identity / prohibited topic" },
  // Additional common abbreviations
  lgb: { normalized: "LGBT", note: "abbreviation for LGBT" },
  lgbti: { normalized: "LGBTI", note: "sexual deviation / prohibited topic" },
  woy: {
    normalized: "woy",
    note: "casual Indonesian interjection/greeting; not SARA/hate/harassment by default",
    safeByDefault: true,
  },
  woi: {
    normalized: "woi",
    note: "casual Indonesian interjection/greeting; not SARA/hate/harassment by default",
    safeByDefault: true,
  },
  oi: {
    normalized: "oi",
    note: "casual call/interjection; not offensive by default",
    safeByDefault: true,
  },
  hadeh: {
    normalized: "hadeh",
    note: "facepalm/tired expression; not offensive by default",
    safeByDefault: true,
  },
  hadeuh: {
    normalized: "hadeh",
    note: "facepalm/tired expression; not offensive by default",
    safeByDefault: true,
  },
};
